#!/usr/bin/env python3
"""Create a private Tag configuration without storing secrets in Git."""

from __future__ import annotations

import argparse
import getpass
import os
import shlex
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def runtime_requirement(package: str) -> str:
    requirements = ROOT / "requirements-runtime.txt"
    prefix = f"{package}=="
    for raw_line in requirements.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line.startswith(prefix):
            return line
    raise RuntimeError(f"{requirements} does not pin {package}")


def ask(prompt: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value or (default or "")


def choose(prompt: str, options: tuple[str, ...], default: str) -> str:
    while True:
        answer = ask(f"{prompt} ({'/'.join(options)})", default).lower()
        if answer in options:
            return answer
        print(f"Choose one of: {', '.join(options)}.")


def ask_secret(prompt: str, prefix: str) -> str:
    while True:
        value = getpass.getpass(f"{prompt}: ").strip()
        if value.startswith(prefix):
            return value
        print(f"Enter the {prefix} token issued by Slack.")


def confirm(prompt: str, default: bool = True) -> bool:
    choice = "Y/n" if default else "y/N"
    answer = input(f"{prompt} [{choice}]: ").strip().lower()
    return default if not answer else answer in {"y", "yes"}


def check_prerequisites(backend: str) -> bool:
    ok = True
    for command, purpose in (("uv", "Python dependency runner"), (backend, "selected CLI backend")):
        found = shutil.which(command)
        print(f"{'✓' if found else '✗'} {command}: {purpose}")
        ok = ok and bool(found)

    if not shutil.which("mfs-server"):
        print("✗ mfs-server: MFS memory server")
        mfs_server_spec = runtime_requirement("mfs-server")
        if shutil.which("uv") and confirm(f"Install {mfs_server_spec} with uv now?"):
            completed = subprocess.run(
                ["uv", "tool", "install", "--force", mfs_server_spec], check=False
            )
            ok = ok and completed.returncode == 0 and shutil.which("mfs-server") is not None
        else:
            ok = False
    else:
        print("✓ mfs-server: MFS memory server")
    return ok


def absolute_directory(prompt: str, default: Path) -> Path:
    while True:
        value = Path(ask(prompt, str(default))).expanduser()
        if value.is_dir():
            return value.resolve()
        print("That directory does not exist. Create it first or choose an existing workspace.")


def zulip_config_path() -> str:
    while True:
        raw = ask("Absolute path to the downloaded Zulip bot zuliprc file")
        path = Path(raw).expanduser()
        if path.is_file():
            return str(path.resolve())
        print("That file was not found. Create the Generic bot in Zulip and download its zuliprc first.")


def render_env(values: dict[str, str]) -> str:
    lines = [
        "# Generated by scripts/opentag_setup.py. Keep this file private.",
        "# It is ignored by Git and is limited to this account (chmod 600).",
        "",
    ]
    for key, value in values.items():
        lines.append(f"export {key}={shlex.quote(value)}")
    lines.append("")
    return "\n".join(lines)


def write_config(path: Path, values: dict[str, str]) -> None:
    path.write_text(render_env(values))
    path.chmod(0o600)
    print(f"\nWrote private configuration: {path}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Guided Tag first-run setup.")
    parser.add_argument("--config", type=Path, default=ROOT / ".env", help="configuration file to create")
    parser.add_argument("--force", action="store_true", help="replace an existing configuration file")
    args = parser.parse_args()
    config_path = args.config.expanduser().resolve()

    if config_path.exists() and not args.force:
        print(f"Refusing to overwrite existing configuration: {config_path}")
        print("Use --force only after backing up values you want to keep.")
        return 1

    print("Tag guided setup\n")
    print("Provider authorization stays in your own browser and terminal.\n")
    transport = choose("Chat transport", ("slack", "zulip", "both"), "slack")
    backend = choose("Agent backend", ("codex", "claude"), "codex")
    workspace = absolute_directory("Workspace the agent may use", ROOT)
    mfs_scope = ask("Allowed MFS scopes (comma-separated)", f"file://local{workspace}")
    values = {
        "MFS_URL": ask("MFS URL", "http://127.0.0.1:13619"),
        "MFS_ALLOWED_SCOPES": mfs_scope,
        "OPENTAG_BACKEND": backend,
        "OPENTAG_BOT_NAME": ask("Bot display name", "OpenMax"),
        "OPENTAG_WORKDIR": str(workspace),
        "OPENTAG_TIMEOUT_SECONDS": ask("Per-task timeout in seconds", "420"),
        "OPENTAG_BACKEND_ATTEMPTS": ask("Backend retry attempts", "3"),
        "OPENTAG_TRANSPORT": transport,
    }
    if transport in {"slack", "both"}:
        print("\nCreate the Slack app from slack-app-manifest.yaml:")
        print("  https://api.slack.com/apps → Create New App → From an app manifest")
        print("Then install it, enable Socket Mode, and create an app token with connections:write.")
        values["SLACK_APP_TOKEN"] = ask_secret("Slack app token", "xapp-")
        values["SLACK_BOT_TOKEN"] = ask_secret("Slack bot token", "xoxb-")
        values["SLACK_CHANNEL_ID"] = ask("Optional sandbox Slack channel ID")
    if transport in {"zulip", "both"}:
        print("\nCreate a Generic Zulip bot, subscribe it to the intended stream, then download its zuliprc file.")
        values["ZULIP_CONFIG_FILE"] = zulip_config_path()
        zulip_engine = choose("Zulip engine", ("native", "zulipmcp"), "native")
        values["OPENTAG_ZULIP_ENGINE"] = zulip_engine
        values["ZULIP_AUTO_GRANT_PRIVATE_HISTORY"] = "false"
        if zulip_engine == "zulipmcp":
            values["OPENTAG_ZULIPMCP_CODEX_PERMISSION_MODE"] = "workspace-write"
            values["OPENTAG_ZULIPMCP_MAX_SESSIONS"] = "1"
            values["OPENTAG_ZULIPMCP_IDLE_HOURS"] = "0.5"
            values["BOT_ALLOWED_PRIVATE_STREAMS"] = ask(
                "Private Zulip streams the MCP agent may access (comma-separated; blank denies all)"
            )
            values["BOT_ALLOWED_WRITE_STREAMS"] = ask(
                "Zulip streams the MCP agent may write (comma-separated; blank uses upstream allow-all default)"
            )

    write_config(config_path, values)
    print("\nChecking local prerequisites:")
    prerequisites_ok = check_prerequisites(backend)
    print("\nNext steps:")
    print("1. Add/index at least one source in MFS that matches MFS_ALLOWED_SCOPES.")
    print("2. Run ./tag start. It starts MFS, runs preflight, and starts the bot.")
    print("3. Mention the bot in the configured sandbox channel.")
    if not prerequisites_ok:
        print("\nFinish the failed prerequisite checks before starting Tag.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
